name: RichardBallard
favicon: null
layout_spectrum: 0
typography_spectrum: 0.2344137
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6784006
  lightness: 0.8153457
  saturation: 0.3620957
  rhythmicContrast: 0.153457
purpose: []
